### ISSUE TITLE
Unable to load the latest sbol OWL rdf file into Protege 5.5.0

### ISSUE THREAD

**Issue by rpgoldman** [dissys/sbol-owl3#3]
When I try, I get this error:

```
  ERROR  12:24:46  An error occurred whilst extracting the Ontology Id from the imported ontology: {}
java.lang.NullPointerException: null
	at org.protege.editor.owl.model.repository.MasterOntologyIDExtractor.getOntologyId(MasterOntologyIDExtractor.java:27) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.checkImport(AnticipateOntologyIdPage.java:109) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.lambda$new$0(AnticipateOntologyIdPage.java:44) [protege-editor-owl.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]
```

I am not sure, but I was wondering if this is related to the ontology header, which reads:

```
<owl:Ontology rdf:about="http://sbols.org/v3"/>
```

But when I look at [the OWL docs](https://www.w3.org/TR/owl-ref/#Header) I see this:

---

The line

    <owl:Ontology rdf:about="">

states that this block describes the current ontology. More precisely, it states the current base URI identifies an instance of the class owl:Ontology. It is recommended that the base URI be defined using an xml:base attribute in the <rdf:RDF> element at the beginning of the document. 

When I replace what's in the file with what the documentation recommends, Protege seems happier, although there are still some other issues.

/cc @jakebeal

**Comment by goksel** [comment]
I can't replicate this issue. I downloaded Protege 5.5.0 (Mac) and it seems to be ok. Could you please test it with other ontologies too? 
Please use this repo: https://github.com/SynBioDex/sbol-owl3
